[package]
name = "sphinx-helper"
version = "3.9.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
cargo_metadata = { workspace = true }
chrono = { workspace = true, features = ["clock"] }
